r"""Generate the paper's performance table body from the consolidated result JSONs
(tables/data/, built by build_dataset.py) so the .tex numbers can't desync from the data.

Run:  python tables/build_tex_tables.py  -> tables/out/perf_tabular.tex (+ full, ranking)
"""
from __future__ import annotations
import json
from pathlib import Path
import numpy as np

HERE = Path(__file__).resolve().parent                        # <suite>/tables/
DATA = HERE / "data"
OUT_DIR = HERE / "out"
OUT = OUT_DIR / "perf_tabular.tex"
OUT_FULL = OUT_DIR / "perf_full_tabular.tex"
OUT_RANK = OUT_DIR / "perf_ranking_tabular.tex"

# appendix ranking table: shared grouped ranking families
RANK_SIDE_PREFIX = {  # (dataset, side) -> metric-key prefix
    ("tech", "seeker"):     "user_grouped_ranking",
    ("tianchi", "seeker"): "user_ranking",
    ("tech", "job"):        "job_ranking",
    ("tianchi", "job"):    "job_ranking",
}
RANK_METRICS = ["GAUC", "MAP@5", "MAP@10", "MAP@20", "Hit@5", "Hit@10", "Hit@20"]

# appendix: every (conv, encoder) variant
VARIANTS = [  # (conv, encoder, block label)
    ("sage",  "qwen3-0.6b", r"SAGE $\cdot$ Qwen3-0.6B (main)"),
    ("gatv2", "qwen3-0.6b", r"GATv2 $\cdot$ Qwen3-0.6B"),
    ("sage",  "qwen3-4b",   r"SAGE $\cdot$ Qwen3-4B"),
    ("sage",  "qwen3-8b",   r"SAGE $\cdot$ Qwen3-8B"),
    ("sage",  "me5",        r"SAGE $\cdot$ multilingual-e5-large"),
]

ENC = "qwen3-0.6b"          # frozen text encoder
CONV = "sage"
KEYS = {                    # headline metric keys (+ cold slices)
    "tech":     {"auc": "auc_exposed.all", "sk": "user_grouped_ranking.GAUC", "jb": "job_ranking.GAUC",
                "skc": None,                     "jbc": "auc_exposed.cold_job"},
    "tianchi": {"auc": "joint_auc",       "sk": "user_ranking.GAUC",         "jb": "job_ranking.GAUC",
                "skc": "joint_auc_cold",         "jbc": "joint_auc_cold_job"},
}
ARMS = [  # (arm file token, row label)
    ("p1", r"content MLP"),
    ("p2", r'content$+$graph (naive)'),
    ("p3", r"graph only"),
    ("p8", r"content$+$graph (decoupled)"),
]
METRIC_ORDER = ("auc", "skc", "jbc", "sk", "jb")   # cold slices after pooled AUC
COLS = [(ds, k) for ds in ("tech", "tianchi") for k in METRIC_ORDER]


def seed_vals(ds: str, arm: str, key: str, conv: str = CONV, enc: str = ENC):
    if KEYS[ds][key] is None:
        return None
    d = json.load(open(DATA / ds / f"{arm}__{conv}__{enc}.json"))
    per = sorted(d["per_seed"], key=lambda ps: ps["seed"])   # align pairs by seed
    vals = [ps["metrics"][KEYS[ds][key]] for ps in per]
    assert len(vals) == 5, f"{ds}/{arm}/{conv}/{enc}: expected 5 seeds, got {len(vals)}"
    return np.asarray(vals, dtype=float)


def seed_mean(ds: str, arm: str, key: str, conv: str = CONV, enc: str = ENC):
    v = seed_vals(ds, arm, key, conv, enc)
    return None if v is None else float(np.mean(v))


def paired_sig(a: np.ndarray, b: np.ndarray, alpha: float = 0.05) -> bool:
    """Two-sided paired t-test over seeds: is mean(a-b) != 0 at level alpha?"""
    from scipy import stats
    d = a - b
    if np.allclose(d.std(ddof=1), 0):
        return False
    t, pval = stats.ttest_rel(a, b)
    return bool(pval < alpha)


def fmt(v: float) -> str:
    return f"{v:.3f}".lstrip("0")          # leading zero omitted


def main() -> None:
    V = {(a, ds, k): seed_mean(ds, a, k) for a, _ in ARMS for ds, k in COLS}
    # best -> bold, second -> underline (per column)
    rank = {}
    for ds, k in COLS:
        if V[(ARMS[0][0], ds, k)] is None:
            rank[(ds, k)] = (None, None)
            continue
        order = sorted(ARMS, key=lambda ar: V[(ar[0], ds, k)], reverse=True)
        rank[(ds, k)] = (order[0][0], order[1][0])
    lines = [
        r"% AUTO-GENERATED by tables/build_tex_tables.py -- DO NOT EDIT BY HAND.",
        r"% Source: tables/data/{tech,tianchi}/<arm>__sage__qwen3-0.6b.json (5-seed mean),",
        r"% metrics = headline keys + cold slices. Re-run after refreshing results.",
        r"\begin{tabular}{lcccccccccc}",
        r"  \toprule",
        r"  & \multicolumn{5}{c}{\textbf{Tech}} & \multicolumn{5}{c}{\textbf{Tianchi}} \\",
        r"  \cmidrule(lr){2-6}\cmidrule(lr){7-11}",
        r"  Model & AUC & Seeker & Job & Seeker & Job & AUC & Seeker & Job & Seeker & Job \\",
        r"        &     & cold AUC & cold AUC & GAUC & GAUC &  & cold AUC & cold AUC & GAUC & GAUC \\",
        r"  \midrule",
    ]
    for a, lbl in ARMS:
        cells = []
        for ds, k in COLS:
            v = V[(a, ds, k)]
            if v is None:
                cells.append(r"---")
                continue
            s = fmt(v)
            first, second = rank[(ds, k)]
            if a == first:
                s = rf"\textbf{{{s}}}"
            elif a == second:
                s = rf"\underline{{{s}}}"
            cells.append(s)
        lines.append(f"  {lbl:34s} & " + " & ".join(cells) + r" \\")
    lines += [r"  \bottomrule", r"\end{tabular}"]
    OUT.parent.mkdir(parents=True, exist_ok=True)
    OUT.write_text("\n".join(lines) + "\n")
    print(f"wrote {OUT.relative_to(HERE.parent)}")
    for ln in lines[3:]:
        print("  " + ln)

    # ---- appendix: full sweep over (conv, encoder) variants -------------------
    flines = [
        r"% AUTO-GENERATED by tables/build_tex_tables.py -- DO NOT EDIT BY HAND.",
        r"% Full conv x encoder sweep; same metric keys as tables/perf_tabular.tex (5-seed mean).",
        r"\begin{tabular}{lcccccccccc}",
        r"  \toprule",
        r"  & \multicolumn{5}{c}{\textbf{Tech}} & \multicolumn{5}{c}{\textbf{Tianchi}} \\",
        r"  \cmidrule(lr){2-6}\cmidrule(lr){7-11}",
        r"  Model & AUC & Seeker & Job & Seeker & Job & AUC & Seeker & Job & Seeker & Job \\",
        r"        &     & cold AUC & cold AUC & GAUC & GAUC &  & cold AUC & cold AUC & GAUC & GAUC \\",
    ]
    for conv, enc, block in VARIANTS:
        W = {(a, ds, k): seed_mean(ds, a, k, conv, enc) for a, _ in ARMS for ds, k in COLS}
        rk = {}
        for ds, k in COLS:
            if W[(ARMS[0][0], ds, k)] is None:
                rk[(ds, k)] = (None, None)
                continue
            order = sorted(ARMS, key=lambda ar: W[(ar[0], ds, k)], reverse=True)
            rk[(ds, k)] = (order[0][0], order[1][0])
        # significance: best vs second-best, per column
        sig = {}
        for ds, k in COLS:
            first, second = rk[(ds, k)]
            if first is None:
                sig[(ds, k)] = False
                continue
            va = seed_vals(ds, first, k, conv, enc)
            vb = seed_vals(ds, second, k, conv, enc)
            sig[(ds, k)] = paired_sig(va, vb)
        flines += [r"  \midrule",
                   rf"  \multicolumn{{11}}{{l}}{{\emph{{{block}}}}} \\[1pt]"]
        for a, lbl in ARMS:
            cells = []
            for ds, k in COLS:
                v = W[(a, ds, k)]
                if v is None:
                    cells.append(r"---")
                    continue
                s = fmt(v)
                first, second = rk[(ds, k)]
                if a == first:
                    star = r"$^{*}$" if sig[(ds, k)] else ""
                    s = rf"\textbf{{{s}}}{star}"
                elif a == second:
                    s = rf"\underline{{{s}}}"
                cells.append(s)
            flines.append(f"  \\quad {lbl:30s} & " + " & ".join(cells) + r" \\")
    flines += [r"  \bottomrule", r"\end{tabular}"]
    OUT_FULL.write_text("\n".join(flines) + "\n")
    print(f"wrote {OUT_FULL.relative_to(HERE.parent)}")

    # ---- appendix: extended ranking metrics (main controlled family) ----------
    def rank_mean(ds, arm, side, m):
        d = json.load(open(DATA / ds / f"{arm}__{CONV}__{ENC}.json"))
        key = f"{RANK_SIDE_PREFIX[(ds, side)]}.{m}"
        vals = [ps["metrics"][key] for ps in d["per_seed"]]
        assert len(vals) == 5, f"{ds}/{arm}/{key}: expected 5 seeds, got {len(vals)}"
        return float(np.mean(vals))

    RCOLS = [(side, m) for side in ("seeker", "job") for m in RANK_METRICS]
    rlines = [
        r"% AUTO-GENERATED by tables/build_tex_tables.py -- DO NOT EDIT BY HAND.",
        r"% Extended grouped ranking metrics, main controlled family (sage/qwen3-0.6b, 5-seed mean).",
        r"% Seeker family: user_grouped_ranking (Tech) / user_ranking (Tianchi); job family: job_ranking.",
        r"\begin{tabular}{lcccccccccccccc}",
        r"  \toprule",
        r"  & \multicolumn{7}{c}{Seeker side} & \multicolumn{7}{c}{Job side} \\",
        r"  \cmidrule(lr){2-8}\cmidrule(lr){9-15}",
        r"  Model & GAUC & M@5 & M@10 & M@20 & H@5 & H@10 & H@20"
        r" & GAUC & M@5 & M@10 & M@20 & H@5 & H@10 & H@20 \\",
    ]
    for ds, block in (("tech", "Tech"), ("tianchi", "Tianchi")):
        R = {(a, side, m): rank_mean(ds, a, side, m) for a, _ in ARMS for side, m in RCOLS}
        rk = {}
        for side, m in RCOLS:
            order = sorted(ARMS, key=lambda ar: R[(ar[0], side, m)], reverse=True)
            rk[(side, m)] = (order[0][0], order[1][0])
        rlines += [r"  \midrule",
                   rf"  \multicolumn{{15}}{{l}}{{\emph{{{block}}}}} \\[1pt]"]
        for a, lbl in ARMS:
            cells = []
            for side, m in RCOLS:
                s = fmt(R[(a, side, m)])
                first, second = rk[(side, m)]
                if a == first:
                    s = rf"\textbf{{{s}}}"
                elif a == second:
                    s = rf"\underline{{{s}}}"
                cells.append(s)
            rlines.append(f"  \\quad {lbl:30s} & " + " & ".join(cells) + r" \\")
    rlines += [r"  \bottomrule", r"\end{tabular}"]
    OUT_RANK.write_text("\n".join(rlines) + "\n")
    print(f"wrote {OUT_RANK.relative_to(HERE.parent)}")


if __name__ == "__main__":
    main()
